var disorders = ["Absence seizure","Abulia","Acute Stress Disorder","Adjustment Disorders","Agoraphobia","Akiltism","Alcohol Addiction", "Alzheimer’s Disease", "Amnesia", "Amphetamine Addiction", "Anorexia Nervosa", "Anterograde Amnesia", "Antisocial personality disorder", "Anxiety Disorder", "Anxiolytic related disorders", "Asperger’s Syndrome", "Attention Deficit Disorder", "Attention Deficit Hyperactivity Disorder", "Autism Spectrum Disorder", "Autophagia", "Avoidant Personality Disorder",
    "Barbiturate related disorders", "Benzodiazepine-related disorders", "Bereavement", "Bibliomania", "Binge Eating Disorder", "Bipolar disorder I", "Bipolar disorder II", "Body Dysmorphic Disorder", "Borderline intellectual functioning", "Borderline Personality Disorder", "Breathing-Related Sleep Disorder", "Brief Psychotic Disorder", "Bruxism", "Bulimia Nervosa",
    "Caffeine Addiction", "Cannabis Addiction", "Catatonic disorder", "Catatonic schizophrenia", "Childhood amnesia", "Childhood Onset Fluency Disorder", "Circadian Rhythm Disorders", "Claustrophobia", "Cocaine related disorders", "Communication disorder", "Conduct Disorder", "Conversion Disorder", "Cotard delusion", "Cyclothymia",
    "Delerium","Delusional Disorder","Dementia", "Dependent Personality Disorder or Asthenic Personality Disorder ", "Depersonalization disorder or Derealization", "Depressive personality disorder", "Derealization disorder", "Dermotillomania", "Desynchronosis", "Developmental coordination disorder", "Diogenes Syndrome", "Disorder of written expression", "Dispareunia", "Dissocial Personality Disorder", "Dissociative Amnesia", "Dissociative Fugue", "Dissociative Identity Disorder or Multiple Personality Disorder", "Down syndrome", "Dyslexia", "Dyspareunia", "Dysthymia or Persistent Depressive Disorder",
    "Eating disorder NOS", "Ekbom’s Syndrome (Delusional Parasitosis)", "Encopresis", "Enuresis (bedwetting)", "Erotomania", "Exhibitionistic Disorder", "Expressive language disorder",
    "Factitious Disorder", "Female Sexual Disorders", "Fetishistic Disorder", "Folie à deux", "Fregoli delusion", "Frotteuristic Disorder", "Fugue State",
    "Ganser syndrome", "Gambling Addiction", "Gender Dysphoria or Gender Identity Disorder", "Generalized Anxiety Disorder", "General adaptation syndrome", "Grandiose delusions",
    "Hallucinogen Addiction", "Haltlose personality disorder", "Histrionic Personality Disorder", "Primary hypersomnia", "Huntington’s Disease", "Hypoactive sexual desire disorder", "Hypochondriasis", "Hypomania", "Hyperkinetic syndrome", "Hypersomnia", "Hysteria",
    "Impulse control disorder", "Impulse control disorder NOS", "Inhalant Addiction", "Insomnia", "Intellectual Development Disorder", "Intermittent Explosive Disorder",
    "Joubert syndrome",
    "Kleptomania", "Korsakoff’s syndrome",
    "Lacunar amnesia", "Language Disorder", "Learning Disorders",
    "Major Depression", "Major depressive disorder", "Male Sexual Disorders", "Malingering", "Mathematics disorder", "Medication-related disorder", "Melancholia", "Intellectual Development Disorder", "Misophonia", "Morbid jealousy", "Munchausen Syndrome", "Munchausen by Proxy",
    "Narcissistic Personality Disorder", "Narcolepsy", "Neglect of child", "Neuroleptic-related disorder", "Nightmare Disorder", "Non Rapid Eye Movement",
    "Obsessive-Compulsive Disorder", "Obsessive-Compulsive Personality Disorder", "Oneirophrenia", "Onychophagia", "Opioid Addiction", "Oppositional Defiant Disorder", "Orthorexia",
    "Pain disorder", "Panic attacks", "Panic Disorder", "Paranoid Personality Disorder", "Parkinson’s Disease", "Partner relational problem", "Passive-aggressive personality disorder", "Pathological gambling", "Pedophilic Disorder", "Perfectionism", "Persecutory delusion", "Personality change due to a general medical condition", "Personality disorder", "Pervasive developmental disorder (PDD)", "Phencyclidine related disorder", "Phobic disorder", "Phonological disorder", "Physical abuse", "Pica", "Polysubstance related disorder", "Postpartum Depression", "Post-traumatic embitterment disorder (PTED)", "Post Traumatic Stress Disorder (PSTD)", "Premature ejaculation", "Premenstrual Dysphoric Disorder", "Psychogenic amnesia", "Psychological factor affecting medical condition", "Psychoneurotic personality disorder", "Psychotic disorder", "Pyromania",
    "Reactive Attachment Disorder", "Reading disorder", "Recurrent brief depression", "Relational disorder", "REM Sleep Behavior Disorder", "Restless Leg Syndrome", "Retrograde amnesia", "Rumination syndrome",
    "Sadistic personality disorder", "Schizoaffective Disorder", "Schizoid Personality Disorder", "Schizophrenia", "Schizophreniform disorder", "Schizotypal Personality Disorder", "Seasonal Affective Disorder", "Sedative, Hypnotic, or Anxiolytic Addiction", "Selective Mutism", "Self-defeating personality disorder", "Separation Anxiety Disorder", "Sexual Disorders Female", "Sexual Disorders Male", "Sexual Addiction", "Sexual Masochism Disorder", "Sexual Sadism Disorder", "Shared Psychotic Disorder", "Sleep Arousal Disorders", "Sleep Paralysis", "Sleep Terror Disorder or Nightmare Disorder", "Social Anxiety Disorder", "Somatization Disorder", "Specific Phobias", "Stendhal syndrome", "Stereotypic movement disorder", "Stimulant Addiction", "Stuttering or Childhood Onset Fluency Disorder", "Substance related disorder",
    "Tardive dyskinesia", "Tobacco Addiction", "Tourettes Syndrome", "Transient tic disorder", "Transient global amnesia", "Transvestic Disorder", "Trichotillomania",
    "Vaginismus", "Voyeuristic Disorder"
];


